<table>
    <tr>
        <td class="col-lg-12 col-sm-12 form-head-text" colspan="2">
            <span> Other Party Details</span>
            <?php $form->addField(["Person","PartyId","Hidden"], ["defaultValue"=>"&{P3}","instanceGroup"=>"P3"]); ?>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Party Type</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "PersonType", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>First Name</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "FirstName", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Middle Name</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "MiddleName", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Last Name</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "LastName", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Suffix</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "NameSuffix", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Vehicle #</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "VehicleUnitNumber", null], ["defaultValue" => "", "instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-12 col-lg-12 fieldInputTd" colspan="2">
            <div><span><?php $form->addField(["Person", "SameAsOwnerAddressGui", null], ["defaultValue" => "", "instanceGroup" => "P3"]); ?>Same As Owner Address (Please check if Owner Address details are keyed in)</span></div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-12 col-lg-12 fieldInputTd" colspan="2">
            <div><span><?php $form->addField(["Person", "SameAsDriverAddressGui", null], ["defaultValue" => "", "instanceGroup" => "P3"]); ?>Same As Driver Address (Please check if Driver Address details are keyed in)</span></div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Address 1</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "Address", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Address 2</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "Address2", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>State</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "State", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>City</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "City", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Zip Code</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "ZipCode", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Home Phone</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "HomePhone", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Date of Birth</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "DateOfBirth", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Driver's License #</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "DriversLicenseNumber", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Driver's License State</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "DriversLicenseJurisdiction", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Injury Code</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "InjuryStatus", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Impairment - Driver</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","AlcoholDrugUse",null], ["instanceGroup"=>"P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td colspan="2" class="item-container citations">
            <div class="item-content">
                <?php $form->addField(["Citations","PartyId",null], ["defaultValue"=>"&{P3}","instanceGroup"=>"P3"]); ?>
                <div class="row m-0">
                    <div class="col-sm-4 col-lg-4 field-label">Action/Arrest/Cites</div>
                    <div class="col-sm-7 col-lg-7 field-input-div">
                        <?php $form->addField(["Citations","CitationDetail",null], ["instanceGroup"=>"P3"]); ?>
                    </div>
                    <a class="add-item col-sm-1 col-lg-1" onclick="javascript:void(0);">(+)</a>
                    <a class="delete-item col-sm-1 col-lg-1 hide" onclick="javascript:void(0);">(-)</a>
                </div>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Passenger Factors</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","PassengerActionsAtTimeOfCrash",null], ["instanceGroup"=>"P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Ped/Bike Factors</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","NonMotoristActionsAtTimeOfCrash",null], ["instanceGroup"=>"P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Equipment</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "SafetyEquipmentRestraint", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Ejected</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "Ejection", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Passenger Taken To:</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "TransportedTo", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
</table>