<table>
    <tr>
        <td class="col-lg-12 col-sm-12 form-head-text" colspan="2">
            <span> Other Party Details</span>
            <?php $form->addField(["Person","PartyId","Hidden"], ["defaultValue"=>"&{P3}","instanceGroup"=>"P3"]); ?>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Party Type</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "PersonType", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>First Name</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "FirstName", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Middle Name</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "MiddleName", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Last Name</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "LastName", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Suffix</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "NameSuffix", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Vehicle #</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "VehicleUnitNumber", null], ["defaultValue" => "", "instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-12 col-lg-12 fieldInputTd" colspan="2">
            <div><span><?php $form->addField(["Person", "SameAsOwnerAddressGui", null], ["defaultValue" => "", "instanceGroup" => "P3"]); ?>Same As Owner Address (Please check if Owner Address details are keyed in)</span></div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-12 col-lg-12 fieldInputTd" colspan="2">
            <div><span><?php $form->addField(["Person", "SameAsDriverAddressGui", null], ["defaultValue" => "", "instanceGroup" => "P3"]); ?>Same As Driver Address (Please check if Driver Address details are keyed in)</span></div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Address 1</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "Address", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Address 2</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "Address2", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>State</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "State", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>City</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "City", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Zip Code</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "ZipCode", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Home Phone</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "HomePhone", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Date of Birth</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "DateOfBirth", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Driver's License #</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "DriversLicenseNumber", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Driver's License State</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "DriversLicenseJurisdiction", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Injury Code</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person", "InjuryStatus", null], ["instanceGroup" => "P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Alcohol/Drugs Suspected</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","AlcoholDrugUse",null], ["defaultValue"=>"","instanceGroup"=>"P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>S2 - Non-Motorist Action</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","NonMotoristActionsAtTimeOfCrash",null], ["defaultValue"=>"","instanceGroup"=>"P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Restraint Use Vehicle</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","SafetyEquipmentRestraint",null], ["defaultValue"=>"","instanceGroup"=>"P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Eject</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","Ejection",null], ["defaultValue"=>"","instanceGroup"=>"P3"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Medical Facility Name</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","TransportedTo",null], ["defaultValue"=>"","instanceGroup"=>"P3"]); ?>
            </div>
        </td>
    </tr>
    
</table>