<table>
    <tr>
        <td class="col-lg-12 col-sm-12 form-head-text" colspan="2">
            <span>Incident Details</span>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-12 col-lg-12 fieldInputTd" colspan="2">
            <div> <span><?php $form->addField(["Incident", "IncidentHitAndRun", null], ["defaultValue" => "1"]); ?>Hit & Run</span></div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Report Identifier # 1</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "CaseIdentifier", null], ["defaultValue" => "", "isRequired"=>true]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Report Identifier # 2</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "StateReportNumber", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Incident Date</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "CrashDate", null], ["defaultValue" => "", "isRequired" => true]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Time (2400)</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "CrashTime", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Incident State</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "LossStateAbbr", null], ["defaultValue" => "", "isRequired"=>true]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Incident City</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "CrashCity", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Report Type</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "ReportTypeId", null], ["defaultValue" => "", "isRequired" => true]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Incident Street</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "LossStreet", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Incident Cross Street</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "LossCrossStreet", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Latitude</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "Latitude", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Longitude</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "Longitude", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>GPS Other</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "GpsOther", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Special Conditions</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "AccidentCondition", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
     <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Number Injured</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "TotalNonfatalInjuries", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
     <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Reporting District</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "Precinct", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Beat</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "Beat", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Officer ID</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "OfficerId", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Number Killed</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "TotalFatalInjuries", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class=" element16_field ">
        <td class="col-sm-12 col-lg-6" colspan="2">
            <div><span>MILE POST INFORMATION</span></div>
        </td>
    </tr>
     <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span class="span-header">Distance</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "MilepostNextStreetDistance", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
     <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span class="span-header">(Ft/Miles)</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "MilepostNextStreetDistanceMeasure", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
     <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span class="span-header">Direction</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "MilepostNextStreetDirection", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
     <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span class="span-header">Milepost Marker</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "Milepost", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>AT INTERSECTION WITH</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <label>
                <?php $form->addField(["Incident", "AccidentAtIntersection", null], ["defaultValue" => ""]); ?>
            </label>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span class="span-header"> OR Distance</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "NextStreetDistance", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span class="span-header">FT/Miles</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "NextStreetDistanceMeasure", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span class="span-header">Direction</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "NextStreetDirection", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span class="span-header">Reference Marker</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "ReferenceMarkers", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect hasChild">
        <td class="col-sm-4 col-lg-4">
            <div><span>Primary Collision Factor List Number (#) of Party at Fault </span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "MostHarmfulEvent", null], ["defaultValue"=>""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field dynamicField Most_Harmful_Event-B hide">
        <td class="col-sm-4 col-lg-4">
            <div><span>Other Description</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "MostHarmfulEventOtherDescription", null], ["defaultValue"=>""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Photographs By:</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div class="row m-0">
                <div class="col-sm-1 p-0">
                    <label class="fit-text-height"><?php $form->addField(['Incident', 'PhotographsByTemp'], ['defaultValue' => 'NONE']); ?></label>
                </div>
                <div class="col-sm-11 p-0">
                    <?php $form->addField(['Incident', 'PhotographsBy'], ['defaultValue' => '']); ?>
                </div>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect hasChild">
        <td class="col-sm-4 col-lg-4">
            <div><span>Weather </span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "WeatherCondition", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field dynamicField Weather_Condition-E hide">
        <td class="col-sm-4 col-lg-4">
            <div><span>Other Description 2</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "WeatherConditionOtherDescription2", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field dynamicField Weather_Condition-F hide">
        <td class="col-sm-4 col-lg-4">
            <div><span>Other Description</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "WeatherConditionOtherDescription", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>    
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Lighting</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "LightCondition", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Road Surface</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "RoadSurfaceCondition", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect hasChild">
        <td class="col-sm-4 col-lg-4">
            <div><span>Road Condition</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "UnusualRoadCondition", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field dynamicField Unusual_Road_Condition-G hide">
        <td class="col-sm-4 col-lg-4">
            <div><span>Other Description </span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "UnusualRoadConditionOtherDescription", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
   <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Traffic Control Devices</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "TrafficControlTypeAtIntersection", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect hasChild">
        <td class="col-sm-4 col-lg-4">
            <div><span>Type of Collision</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "CrashType", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field dynamicField Crash_Type-H hide">
        <td class="col-sm-4 col-lg-4">
            <div><span>Other Description </span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "CrashTypeDescription", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect hasChild">
        <td class="col-sm-4 col-lg-4">
            <div><span>Motor Vehicle Involved With</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "MotorVehicleInvolvedWith", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field dynamicField Motor_Vehicle_Involved_With-H hide">
        <td class="col-sm-4 col-lg-4">
            <div><span>Other Description </span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "MotorVehicleInvolvedWithAnimalDescription", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field dynamicField Motor_Vehicle_Involved_With-I hide">
        <td class="col-sm-4 col-lg-4">
            <div><span>Fixed Object Description</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "MotorVehicleInvolvedWithFixedObjectDescription", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field dynamicField Motor_Vehicle_Involved_With-J hide">
        <td class="col-sm-4 col-lg-4">
            <div><span>Other Object Description</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Incident", "MotorVehicleInvolvedWithOtherObjectDescription", null], ["defaultValue" => ""]); ?>
            </div>
        </td>
    </tr>
</table>