
<?php $this->headLink()
    ->prependStylesheet($this->basePath('css/metrics.css'))
    ->prependStylesheet($this->basePath('library/datatables/dataTables.bootstrap.css'));
    
    $this->headScript()
    ->appendFile($this->basePath('library/datatables/jquery.dataTables.1.10.15.min.js'))
    ->appendFile($this->basePath('library/datatables/dataTables.bootstrap.1.10.15.js'))
    ->appendFile($this->basePath('js/admin/auto-extraction-report.js'));
?>

<script type="text/javascript">
    $(function(){
        stripeTable($('table.default'));
        $( ".hasCalendar" ).datepicker();
    });
</script>

<h1>Auto Vs Manual Report</h1>

<div class="col-md-6 col-md-offset-3">
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('auto-extraction-metrics', ['action' => 'auto-extraction-report']));
    $form->setAttribute('enctype', 'application/x-www-form-urlencoded');
    $form->setAttribute('id', 'getAutoVsManualReport');
    $form->prepare();
    ?>

    <?= $this->form()->openTag($form); ?>
    <?= $this->formElement($form->get('csrf'));?>
    <fieldset>
        <legend>Keying Date</legend>
        <div class="field-label-group">
            <?= $this->formLabel($form->get('fromDate')); ?>
            <?= $this->formElement($form->get('fromDate')); ?>
        </div>
        <div class="field-label-group">
            <?= $this->formLabel($form->get('toDate')); ?>
            <?= $this->formElement($form->get('toDate')); ?>
        </div>
        <div class="note-txt">Note: Please select date range between <?= $reportDuration; ?> days.</div>
    </fieldset>

    <fieldset>
        <legend>State</legend>
        <div class="field-label-group">
            <?= $this->formLabel($form->get('state')); ?>
            <?= $this->formElement($form->get('state')); ?>
        </div>
    </fieldset>
    
    <?php if ($this->isLNUser): ?>
    <fieldset>
        <legend>Company</legend>
        <div class="field-label-group">
            <?= $this->formLabel($form->get('keyingVendorId')); ?>
            <?= $this->formElement($form->get('keyingVendorId')); ?>
        </div>
    </fieldset>
    <?php else: ?>
        <?= $this->formElement($form->get('keyingVendorId')); ?>
    <?php endif; ?>
    
    <?= $this->formElement($form->get('submit')); ?>
</div>

<div class="result" style="margin: 40px 5px 5px 5px;">
    <div id="auto-extraction-dataTable-container" class="dataTable-container hide">
        <table class="table dataTable commonListingTable" id="auto-extraction-dataTable">
            <thead>
                <tr>
                    <th>State</th>
                    <th>Report ID</th>
                    <th>Work Type</th>
                    <th>Creation Date</th>
                    <th>Report Status</th>
                    <th>Auto Extraction</th>
                    <th>Auto/Manual</th>
                    <th>Auto Extraction Date</th>
                    <th>Pass1 User</th>
                    <th>Pass1 Start Date</th>
                    <th>Pass1 End Date</th>
                    <th>Pass2 User</th>
                    <th>Pass2 Start Date</th>
                    <th>Pass2 End Date</th>
                    <th>Pass1 Duration</th>
                    <th>Pass2 Duration</th>
                    <th>Total&nbsp;Time&nbsp;Spent (Per&nbsp;Report)</th>
                    <?php if ($this->isLNUser): ?><th>Company Name</th><?php endif; ?>
                </tr>
            </thead>
        </table>
    </div>
</div>

<div class="export" style="margin: 15px 0px;">
    <?= $this->formElement($form->get('export')); ?>
</div>
<?= $this->form()->closeTag(); ?>
