<table>
    <tr>
        <td class="col-lg-12 col-sm-12 form-head-text" colspan="2">
            <span>Owner Details</span>
        </td>
    </tr>
    <tr class="hide">
        <td class="col-sm-4 col-lg-4">
            <div><span></span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","PartyId","Hidden"], ["defaultValue"=>"&{P2}","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="hide">
        <td class="col-sm-4 col-lg-4">
            <div><span></span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","VehicleUnitNumber","Hidden"], ["defaultValue"=>"&{V1}","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="hide">
        <td class="col-sm-4 col-lg-4">
            <div><span></span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","PersonType","Hidden"], ["defaultValue"=>"VEHICLE OWNER","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>First Name</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","FirstName",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Middle Name</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","MiddleName",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Last Name</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","LastName",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Suffix</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","NameSuffix",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Sex</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","Sex",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr>
        <td class="col-sm-12 col-lg-12 fieldInputTd" colspan="2">
            <div> <span><?php $form->addField(["Person","SameAsDriverAddressGui",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>Same As Driver Address (Please check if Driver Address details are keyed in)</span></div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Address 1</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","Address",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Address 2</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","Address2",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>State</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","State",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>City</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","City",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Zip Code</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","ZipCode",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Home Phone</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","HomePhone",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Date of Birth</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","DateOfBirth",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Driver's License #</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","DriversLicenseNumber",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Driver's License State</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","DriversLicenseJurisdiction",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Injury Code</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","InjuryStatus",null], ["defaultValue"=>"","instanceGroup"=>"P2"]); ?>
            </div>
        </td>
    </tr>
    <tr>
        <td class="col-lg-12 col-sm-12 form-head-text" colspan="2">
            <span>Driver Details</span>
        </td>
    </tr>
    <tr class="hide">
        <td class="col-sm-4 col-lg-4">
            <div><span></span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","PartyId","Hidden"], ["defaultValue"=>"&{P1}","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="hide">
        <td class="col-sm-4 col-lg-4">
            <div><span></span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","VehicleUnitNumber","Hidden"], ["defaultValue"=>"&{V1}","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="hide">
        <td class="col-sm-4 col-lg-4">
            <div><span></span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","PersonType","Hidden"], ["defaultValue"=>"DRIVER","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-12 col-lg-12 fieldInputTd" colspan="2">
            <div> <span><?php $form->addField(["Person","SameAsDriverGui",null], ["defaultValue"=>"Y","instanceGroup"=>"P1"]); ?>Same As Owner</span></div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>First Name</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","FirstName",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Middle Name</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","MiddleName",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Last Name</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","LastName",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Suffix</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","NameSuffix",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Sex</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","Sex",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Address 1</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","Address",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Address 2</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","Address2",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>State</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","State",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>City</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","City",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Zip Code</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","ZipCode",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Home Phone</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","HomePhone",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Date of Birth</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","DateOfBirth",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Driver's License #</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","DriversLicenseNumber",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Driver's License State</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","DriversLicenseJurisdiction",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Injury Code</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","InjuryStatus",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Suspected Alcohol Use</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","AlcoholUseSuspected",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Suspected Drug Use</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","DrugUseSuspected",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Alcohol Tested </span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","AlcoholTestStatus",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>BAC</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","AlcoholTestResult",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Violations</span></div>
        </td>
        <td class="col-sm-4 col-lg-4">
            <a class="add-item" onclick="javascript:void(0);">(+) Add Entry</a>
        </td>
    </tr>
    <tr class="element16_field">
        <td colspan="2" class="item-container citations">
            <div class="item-content">
                <?php $form->addField(["Citations","PartyId",null], ["defaultValue"=>"&{P1}","instanceGroup"=>"P1"]); ?>
                <div class="row m-0">
                    <div class="col-sm-4 col-lg-4 field-label">Charge</div>
                    <div class="col-sm-7 col-lg-7 field-input-div">
                        <?php $form->addField(["Citations","CitationDetail",null], ["instanceGroup"=>"P1"]); ?>
                    </div>
                    <a class="delete-item col-sm-1 col-lg-1 hide" onclick="javascript:void(0);">(-)</a>
                </div>
                <div class="row m-0">
                    <div class="col-sm-4 col-lg-4 field-label">Citation Number</div>
                    <div class="col-sm-7 col-lg-7 field-input-div">
                        <?php $form->addField(["Citations","CitationNumber",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
                    </div>
                </div>
                <div class="row m-0">
                    <div class="col-sm-4 col-lg-4 field-label">FL Statute Number</div>
                    <div class="col-sm-7 col-lg-7 field-input-div">
                        <?php $form->addField(["Citations","ViolationCode",null], ["instanceGroup"=>"P1"]); ?>
                    </div>
                </div>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Drivers Actions at Time of Crash</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","DriverActionsAtTimeOfCrash",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Non-Motorist Actions/Circumstances</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","NonMotoristActionsAtTimeOfCrash",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Driver Distracted By</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","DriverDistractedBy",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Condition At time of Crash </span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","ConditionAtTimeOfCrash",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Restraint Systems</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","SafetyEquipmentRestraint",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Ejection</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","Ejection",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Helmet Use</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","SafetyEquipmentHelmet",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Medical Facility Transported To</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Person","TransportedTo",null], ["defaultValue"=>"","instanceGroup"=>"P1"]); ?>
            </div>
        </td>
    </tr>
    <tr>
        <td class="col-lg-12 col-sm-12 form-head-text" colspan="2">
            <span>Vehicle Details</span>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Vehicle #</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","UnitNumber",null], ["defaultValue"=>"&{V1}","instanceGroup"=>"V1", "isRequired"=>true]); ?>
            </div>
        </td>
    </tr>
    <tr class="add-trailer">
        <td class="col-sm-4 col-lg-4">
            <div><span>Add Trailer</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","AddTrailerGui",null], ["defaultValue"=>"Add Trailer","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-12 col-lg-12 fieldInputTd" colspan="2">
            <div> <span><?php $form->addField(["Vehicle","CommercialVehicle",null], ["defaultValue"=>"1", 'instanceGroup' => 'V1']); ?>Check If Commercial</span></div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Tag #</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","LicensePlate",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Tag State</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","RegistrationState",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field vinNumber">
        <td class="col-sm-4 col-lg-4">
            <div><span>VIN</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
              <?php $form->addField(["Vehicle","Vin",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
              <?php $form->addField(['Vehicle', 'VinStatus'], ['instanceGroup' => 'V1']); ?>
              <?php $form->addField(['Vehicle', 'VinOriginal'], ['instanceGroup' => 'V1']); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Year</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","ModelYear",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
                <?php $form->addField(['Vehicle', 'ModelYearOriginal',null], ['instanceGroup' => 'V1']); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Make</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","Make",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
                <?php $form->addField(['Vehicle', 'MakeOriginal',null], ['instanceGroup' => 'V1']); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Model</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","Model",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
                <?php $form->addField(['Vehicle', 'ModelOriginal',null], ['instanceGroup' => 'V1']); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Insurance Carrier</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","InsuranceCompany",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Policy #</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","InsurancePolicyNumber",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="elem_nonprior">
        <td class="col-sm-4 col-lg-4">
            <div><span>Policy Exp. Date</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","InsuranceExpirationDate",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Vehicle Towed</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <label>
                    <?php $form->addField(['Vehicle', 'VehicleTowed'], ['defaultValue' => '1', 'instanceGroup' => 'V1']); ?>Yes
                </label>
                <label>
                    <?php $form->addField(['Vehicle', 'VehicleTowed'], ['defaultValue' => '0', 'instanceGroup' => 'V1']); ?>No
                </label>
                <label>
                    <?php $form->addField(['Vehicle', 'VehicleTowed'], ['defaultValue' => '', 'instanceGroup' => 'V1', 'isDefaultSelection' => true]); ?>NA
                </label>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Airbag Deployed</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <label>
                    <?php $form->addField(['Vehicle', 'AirBagDeployed'], ['defaultValue' => '1', 'instanceGroup' => 'V1']); ?>Yes
                </label>
                <label>
                    <?php $form->addField(['Vehicle', 'AirBagDeployed'], ['defaultValue' => '0', 'instanceGroup' => 'V1']); ?>No
                </label>
                <label>
                    <?php $form->addField(['Vehicle', 'AirBagDeployed'], ['defaultValue' => '', 'instanceGroup' => 'V1', 'isDefaultSelection' => true]); ?>NA
                </label>
            </div>
        </td>
    </tr>
    <tr class="critical_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Impact Location</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","DamagedAreas",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Vehicle Defects</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","ContributingCircumstancesVehicle",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field">
        <td class="col-sm-4 col-lg-4">
            <div><span>Posted Speed</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","PostedStatutorySpeedLimit",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Vehicle Body type</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","UnitType",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Vehicle Maneuver Action</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","VehicleManeuverActionPrior",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Most Harmful Event</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","MostHarmfulEventForVehicle",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Sequence of Events</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","EventSequence",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Trafficway</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","TrafficwayDescription",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
    <tr class="element16_field multiselect">
        <td class="col-sm-4 col-lg-4">
            <div><span>Traffic Control Device for This Vehicle</span></div>
        </td>
        <td class="col-sm-8 col-lg-8 fieldInputTd">
            <div>
                <?php $form->addField(["Vehicle","TrafficControlDeviceType",null], ["defaultValue"=>"","instanceGroup"=>"V1"]); ?>
            </div>
        </td>
    </tr>
</table>