<table style="width: 100%;" class="text-center">
    <tr>
        <td class="box-top-left">&nbsp;</td>
        <td class="box-top-bg" align="left">
            <h3>Password Reset</h3>
        </td>
        <td class="box-top-right">&nbsp;</td>
    </tr>
    <tr>
        <td class="box-leftbg">&nbsp;</td>
        <td class="contentgridarea" style="border:1px solid #e2ddde;">
            <form name="showhistoricnotes" id="showhistoricnotes" method="post" action="<?php 
                echo $this->url('users',
                    ['action' => 'resetPasswordPopup'],
                    ['query' => $requestParams]
                );?>">
                
                <!-- The content would be populated here -->
                <table>
                    <tr>
                        <td>
                            <span style="font-size: medium;">
                                <?php if (!$this->passwordSent): ?>
                                    Password for the user has been reset, but could not be sent to E-mail Address. Please contact the Administrator
                                <?php else: ?>
                                    Password for the user has been reset and sent to E-mail Address
                                <?php endif; ?>
                            </span>
                        </td>
                    </tr>
                </table>
            </form>
        </td>
        <td class="box-rightbg">&nbsp;</td>
    </tr>
    <tr>
        <td class="box-leftbg"></td>
        <td class="contentgridarea" style="border:1px solid #e2ddde;">
            <table class="text-center">
                <tr>
                    <td>
                        <?= $this->formElement($form->get('ok'));?>
                    </td>
                </tr>
            </table>
        <td class="box-rightbg"></td>
    </tr>
    <tr>
        <td class="box-bot-left">&nbsp;</td>
        <td class="box-bot-bg">&nbsp;</td>
        <td class="box-bot-right">&nbsp;</td>
    </tr>
</table>