<?php
$this->headLink()
    ->appendStylesheet($this->basePath() . '/css/common-form.css');
$this->headScript()
    ->appendFile($this->basePath('/js/init-form-objects.js'))
    ->appendFile($this->basePath('/js/common/notes.js'));
?>
<script>
    var imageWindow = createImageWindow();
    imageWindow.openWindow('/data/report-entry/image-viewer-pdf');
</script>
<iframe 
    id="formIframe" 
    frameBorder="0" 
    src="<?= $this->basePath() . '/data/report-entry/display'?>">
</iframe>
