
<div class="ui-widget ui-widget-content ui-corner-all m-auto" style="width: 90%; text-align: left; padding: 0.2em;">
    <div class="ui-widget-header ui-corner-all" style="padding: 0.4em 1em;"><h3>Image Entry</h3></div>

    <div class="ui-helper-clearfix" style="padding: 0px 20px;">
        <?php
            $form->setAttribute('enctype', 'application/x-www-form-urlencoded');
            $form->prepare();

        ?>

        <?= $this->form()->openTag($form); ?>
        <dl class="zend_form">
            <dd id="csrf-element"><?= $this->formElement($form->get('csrf'));?></dd>
            <dt id="addKeying-label"><?= $this->formLabel($form->get('addKeying')); ?></dt>
            <dd id="addKeying-element"><?= $this->formElement($form->get('addKeying')); ?></dd>
            <dt id="workType-label"><?= $this->formLabel($form->get('workType')); ?></dt>
            <dd id="workType-element"><?= $this->formElement($form->get('workType')); ?></dd>
            <dt id="submit-label">&nbsp;</dt>
            <dd id="submit-element"><?= $this->formElement($form->get('submit')); ?></dd>  
        </dl>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<script type="text/javascript"><?php $this->inlineScript()->captureStart(); ?>
    $(function() {
        $('#selectWorkType').submit(function() {
            $('#submit')
                .css('background-color', 'silver')
                .val('Processing...')
                .attr('disabled', 'disabled');
                        $("#selectWorkType #workType").removeAttr('disabled');
        });
    })
        
        $("#selectWorkType #addKeying").change(function() {
            if ($(this).val() == 1) {
                $("#selectWorkType #workType").val('1');    
                $("#selectWorkType #workType").attr('disabled', 'disabled');
            } else {
                $("#selectWorkType #workType").removeAttr('disabled');
            }
        });  
<?php $this->inlineScript()->captureEnd(); ?></script>