<?php $this->headLink()->appendStylesheet($this->basePath() . '/css/change-user-password.css'); ?>
<table width="90%" border="0" cellspacing="0" cellpadding="0" align="center" id="change-user-password">
    <tr>
        <td class="box-top-left">&nbsp;</td>
        <td class="box-top-bg" align="left">
            <h3>Change Password</h3>
        </td>
        <td class="box-top-right">&nbsp;</td>
    </tr>
    <?php if (!empty($this->messages)): ?>
    <tr>
        <td class="box-leftbg">&nbsp;</td>
        <td class="contentgridarea" style="border:1px solid #e2ddde; ">
            <table>
                <tr><td>
                <ul class="flashmessage">
                    <li><?php print $this->messages;?></li>
                </ul>
                    </td>
             </tr>
            </table>
        </td>
        <td class="box-rightbg">&nbsp;</td>
    </tr>
    <?php endif?>
    <form name="usermanagement" id="usermanagement" method="post" autocomplete="off" action=" ">
        <tr>
           <td class="box-leftbg">&nbsp;</td>
           <td class="contentgridarea" style="border:1px solid #e2ddde; " align="left">
            <table cellspacing="5" cellpadding="0"  border="0" width="100%" align="left">
                <tr><td colspan="2">
            <label>Your password must be at least 8 characters long and must contain 3 of the following : </label></td></tr>
            <tr>
                <td align="left" width="65%" class="bullet">
                    <ul class="bulletedList">
                <li>Lower-case letter</li>
                <li>Upper-case letter</li>
                <li>Number</li>
                <li>Special Character</li>
                 </ul></td><td width="85%">&nbsp;</td></tr>
            </table>
        </td>
           <td class="box-rightbg">&nbsp;</td>
      </tr>
      <tr>
        <td class="box-leftbg">&nbsp;</td>
        <td class="contentgridarea" style="border:1px solid #e2ddde; " align="center">
 
     <table cellspacing="5" cellpadding="0" class="table borderless"   border="0" width="50%" align="left">
     
        <tbody>
            <tr>
                <td align="right" width="35%"><label>User ID</label> <span style="color:#F00">*</span></td>
                <td align="left" width="65%"><?= $this->formElement($form->get('username'));?></td>
            </tr>
            <tr>
                <td align="right" ><label>Current Password</label> <span style="color:#F00">*</span>
                    <div class="divTempPwd">
                        <input type="password" class="inpTempPwd" id="tempPwd1" autocomplete="off" />
                    </div>
                </td>
                <td align="left" ><?= $this->formElement($form->get('passwordCurrent')); ?></td>
            </tr>
            <tr>
                <td align="right" >
                    <label>New Password </label><span style="color:#F00">*</span>
                    <div class="divTempPwd">
                        <input type="password" class="inpTempPwd" id="tempPwd2" autocomplete="off" />
                    </div>
                </td>
                <td align="left" ><?= $this->formElement($form->get('passwordNew'));?></td>
            </tr>
            <tr>
                <td align="right" ><label>Confirm New Password </label><span style="color:#F00">*</span>
                    <div class="divTempPwd">
                        <input type="password" class="inpTempPwd" id="tempPwd3" autocomplete="off" />
                    </div>
                </td>
                <td align="left"><?= $this->formElement($form->get('passwordConfirm')); ?></td>
            </tr>
        </tbody>
    </table>
        </td>
        <td class="box-rightbg">&nbsp;</td>
      </tr>
      <tr>
        <td class="box-leftbg">&nbsp;</td>
        <td class="contentgridarea" style="border:1px solid #e2ddde; " align="left">
            <table  class="table borderless" align="left" border="0" style="width:35%" cellpadding="2" cellspacing="3">
                <tr >
                    <td  align="right" width="10%"><?= $this->formElement($form->get('save'));?></td>
                       <td  align="left" ><?= $this->formElement($form->get('cancel'));?></td>
            </tr></table>
        </td>
        <td class="box-rightbg">&nbsp;</td>
      </tr>
      </form>
      <tr>
        <td class="box-bot-left">&nbsp;</td>
        <td class="box-bot-bg">&nbsp;</td>
        <td class="box-bot-right">&nbsp;</td>
      </tr>
    </table>