<!-- Code to bring the focus to the first HTML input box by default -->
<script type="text/javascript">
    window.onload = setCursorFocus;
</script>

<?php if (!empty($this->resultMessage)): ?>
    <table width="90%" border="0" cellspacing="0" cellpadding="0" align="center">
        <tr align="left">
            <td class="box-top-left">&nbsp;</td>
            <td class="box-top-bg"></td>
            <td class="box-top-right">&nbsp;</td>
        </tr>
        <tr>
            <td class="box-leftbg">&nbsp;</td>
            <td class="contentgridarea" style="border:1px solid #e2ddde; " align="center">
                <?= $this->resultMessage ?><br>
            </td>
            <td class="box-rightbg">&nbsp;</td>
        </tr>
        <tr>
            <td class="box-leftbg">&nbsp;</td>
            <td class="contentgridarea" style="border:1px solid #e2ddde; " align="left">
                <table align="left" border="0" width="100%" cellpadding="2" cellspacing="2">
                    <tr>
                        <td align="center" width="9%"><input type="button" value="  OK  " class="btnstyle" onclick="redirectToLogin()"></td>
                    </tr>
                </table>
            </td>
            <td class="box-rightbg">&nbsp;</td>
        </tr>
        <tr>
            <td class="box-bot-left">&nbsp;</td>
            <td class="box-bot-bg">&nbsp;</td>
            <td class="box-bot-right">&nbsp;</td>
        </tr>
    </table>
<?php else: ?>
<form name="usermanagement" id="usermanagement" method="post" autocomplete="off" action=" ">
     <?= $this->formElement($form->get('csrf')); ?>
<table width="90%" border="0"  cellspacing="0" cellpadding="0" align="center">
      <tr>
        <td class="box-top-left">&nbsp;</td>
        <td class="box-top-bg" align="left"> <h3>Change Password</h3> </td>
        <td class="box-top-right">&nbsp;</td>
      </tr>
         <?php if (!empty($this->errorMessage)): ?>
    <tr>
        <td class="box-leftbg">&nbsp;</td>
        <td class="contentgridarea" style="border:1px solid #e2ddde; ">
            <table>
                <tr>
                <td class="errorMsg">
                    <?php foreach ($this->errorMessage as $error) echo $error . '<br />'; ?>
                </td>
               </tr>
            </table>
        </td>
        <td class="box-rightbg">&nbsp;</td>
    </tr>
    <?php endif; ?>
          <tr>
           <td class="box-leftbg">&nbsp;</td>
           <td class="contentgridarea" style="border:1px solid #e2ddde; " align="left">
            <table cellspacing="5" cellpadding="0"  border="0" width="100%" align="left">
                <tr><td colspan="2">
            <label>Your password must be at least 8 characters long and must contain 3 of the following : </label></td></tr>
            <tr>
                <td align="left" width="65%" class="bullet">
                    <ul class="bulletedList">
                <li>Lower-case letter</li>
                <li>Upper-case letter</li>
                <li>Number</li>
                <li>Special Character</li>
                 </ul></td>
                 <td width="85%">&nbsp;</td>
            </tr>
            </table>
        </td>
           <td class="box-rightbg">&nbsp;</td>
      </tr>
      <tr>
        <td class="box-leftbg">&nbsp;</td>
        <td class="contentgridarea" style="border:1px solid #e2ddde; " align="center">
     <table cellspacing="5" cellpadding="0" class="table borderless"  border="0" width="50%" align="left">
        <tbody>
            <tr><input type="hidden" value="<?= $this->loginId; ?>" name="loginId">
            <input type="hidden" value="<?= $this->loginId; ?>" name="username">
            <input type="hidden" value="<?= $this->sessionId; ?>" name="session_id">
                <td align="right" width="30%"><label>Current Password</label> <span style="color:#F00">*</span>
                    <div class="divTempPwd">
                        <input type="password" class="inpTempPwd" id="tempPwd1" autocomplete="off" />
                    </div>
                </td>
                <td align="left" width="70%"><?= $this->formElement($form->get('passwordCurrent')); ?></td>
            </tr>
            <tr>
                <td align="right" ><label>New Password </label><span style="color:#F00">*</span>
                    <div class="divTempPwd">
                        <input type="password" class="inpTempPwd" id="tempPwd2" autocomplete="off" />
                    </div>
                </td>
                <td align="left" ><?= $this->formElement($form->get('passwordNew')); ?></td>
            </tr>
            <tr>
                <td align="right" ><label>Confirm Password </label><span style="color:#F00">*</span>
                    <div class="divTempPwd">
                        <input type="password" class="inpTempPwd" id="tempPwd3" autocomplete="off" />
                    </div>
                </td>
                <td align="left"><?= $this->formElement($form->get('passwordConfirm')); ?></td>
            </tr>
        </tbody>
    </table>
        </td>
        <td class="box-rightbg">&nbsp;</td>
      </tr>
    <?php if (empty($sec_questions)): ?>
    <tr>
        <td class="box-leftbg">&nbsp;</td>
        <td class="contentgridarea" style="border:1px solid #e2ddde; " align="center">
            <table align="left" border="0" cellpadding="0" cellspacing="5">
                <tr><td align="left" colspan="3"><h3>Security Check <span style="color:#F00">*</span></h3></td></tr>
                
                <?php for($i = 1; $i <= 4; $i ++): ?>
                    <tr>
                        <td width="20%" align="right"><label>Security Question</label></td>
                        <td width="39%"><?= $this->formElement($form->get('question_' . $i . ''));?></td>
                        <td width="75%" align="left"><?= $this->formElement($form->get('answer_' . $i . ''));?></td>
                    </tr>
                <?php endfor; ?>
            </table>
        </td>
        <td class="box-rightbg">&nbsp;</td>
    </tr>
    <?php endif; ?>
    <tr>
        <td class="box-leftbg">&nbsp;</td>
        <td class="contentgridarea" style="border:1px solid #e2ddde; " align="left">
            <table align="left" border="0">
                <tr align="left">
                    <td><?= $this->formElement($form->get('save')); ?></td>
            </tr></table>
        </td>
        <td class="box-rightbg">&nbsp;</td>
    </tr>
    <tr>
        <td class="box-bot-left">&nbsp;</td>
        <td class="box-bot-bg">&nbsp;</td>
        <td class="box-bot-right">&nbsp;</td>
      </tr>
    </table>
</form>
<?php endif; ?>
