<div class='clear'></div>
<table width="90%"  border="0" cellspacing="0" cellpadding="0" align="center" >
	<tr align="left">
		<td class="box-top-left">&nbsp;</td>
		<td class="box-top-bg"><h3>Forgot Password</h3></td>
		<td class="box-top-right">&nbsp;</td>
	  </tr>
        <?php if (! empty($this->errorMessage)) : ?>
	<tr>
		<td class="box-leftbg">&nbsp;</td>
		<td class="contentgridarea" style="border:1px solid #e2ddde; ">
			<table>
				<tr><td class="errorMsg">
					<?= $this->errorMessage; ?>
					</td>
			 </tr>
			</table>
		</td>
		<td class="box-rightbg">&nbsp;</td>
	</tr>  <?php endif; ?>
	 <form name="forgotpassword" id="forgotpassword" method="post" action="<?= $this->url();?>">
	  <tr>
		<td class="box-leftbg">&nbsp;</td>
		<td class="contentgridarea" style="border:1px solid #e2ddde; " align="center">


	 <table  class="table borderless" cellspacing="5" cellpadding="0" border="0" style="width:35%" align="left">

			<tr>
				<td align="right" width="31%">User ID <span style="color:#F00">*</span></td>
				<td align="left" ><?=   $this->formElement($form->get('username'));?></td>
			</tr>
			<tr>
				<td align="right" width="31%">Email Address <span style="color:#F00">*</span></td>
				<td align="left" ><?= $this->formElement($form->get('email'));?></td>
			</tr>
	</table>

		</td>
		<td class="box-rightbg">&nbsp;</td>
	  </tr>
	 <tr>
		<td class="box-leftbg">&nbsp;</td>
		<td class="contentgridarea" style="border:1px solid #e2ddde; " align="left">
			<table  class="table borderless" align="left" border="0" style="width:35%" cellpadding="2" cellspacing="3">
				<tr >
					<td  align="right" width="10%"><?= $this->formElement($form->get('submit'));?></td>
					   <td  align="left" ><?= $this->formElement($form->get('cancel'));?></td>
			</tr></table>

		</td>
		<td class="box-rightbg">&nbsp;</td>
	  </tr>

	 </form>
	  <tr>
		<td class="box-bot-left">&nbsp;</td>
		<td class="box-bot-bg">&nbsp;</td>
		<td class="box-bot-right">&nbsp;</td>
	  </tr>
	</table>
